### ISSUE TITLE
Update the documentation: Suggest pip instead of apt-get

### ISSUE THREAD

**Issue by piratimir** [BirdCode/pylanos#1]
apt-get is a tool for installing packages on Debian based distros. It does the job but we as python coders should make use of our package manager (pip) so others can install dependencies of our app in every platform that supports pip.

**Comment by antikola** [comment]
Give me some details.

**Comment by antikola** [comment]
ketu*

**Comment by piratimir** [comment]
Update the README.md file. When you see apt-get install python-package-here replace the apt-get with pip.
